server:
  port: 5001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/Keycloak
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/



#  spring.application.name=Online-Food-Ordering
#  spring.datasource.url=jdbc:postgresql://localhost:5432/dineYard
#  spring.datasource.username=postgres
#  spring.datasource.password=password
#
#  #ddl = data definition language
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=true

