server:
  port: 5001

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/Keycloak
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8087/realms/MyRealm
          jwk-set-uri: http://localhost:8087/realms/MyRealm/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: TaskHub
      principal-attribute: principal_username

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/



#  spring.application.name=Online-Food-Ordering
#  spring.datasource.url=jdbc:postgresql://localhost:5432/dineYard
#  spring.datasource.username=postgres
#  spring.datasource.password=password
#
#  #ddl = data definition language
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=true

